name: Scrape LTC Python

on:
  repository_dispatch:
    types:
      - ltc
  schedule:
    - cron: '20 22 * * *'

defaults:
  run:
     working-directory: data-collection-scripts/ltc-scrapers/python-scrapers

jobs:
  scrape:
      runs-on: ubuntu-18.04
      strategy:
        fail-fast: false
        matrix:
          state: [ks, ut]
      steps:
        - uses: actions/checkout@v2
        - uses: actions/cache@v2
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
              ${{ runner.os }}-pip-
        - name: Use Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.9'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: Run scraper
          run: |
            python ${{ matrix.state }}_ltc_scraper.py > ../../../data/ltc_states/ltc_${{ matrix.state }}.csv
        - name: Commit
          if: github.ref == 'refs/heads/master'
          uses: EndBug/add-and-commit@v5
          with:
            message: Updating scraped LTC data
            add: data/ltc_states/ltc_${{ matrix.state }}.csv
            author_name: GitHub Actions
            author_email: actions@github.com
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}